name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"include\": [{\"os\": \"ubuntu-latest\", \"node\": \"20\"}]}" >> "$GITHUB_OUTPUT"

  test:
    needs: build
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    steps:
      - run: npm test